// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUWxRLUj2QIJvmiLGQFbKkqZSOcBccY0',
    appId: '1:1010428449178:web:1aa26bfbb33f6cd8242a23',
    messagingSenderId: '1010428449178',
    projectId: 'rumour-90460',
    authDomain: 'rumour-90460.firebaseapp.com',
    storageBucket: 'rumour-90460.firebasestorage.app',
    measurementId: 'G-XM01EP5J6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu5QyCA5ANCFv9N_H1QqFxzVDWE1tE20s',
    appId: '1:1010428449178:android:285985944c5d02ee242a23',
    messagingSenderId: '1010428449178',
    projectId: 'rumour-90460',
    storageBucket: 'rumour-90460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJAbn9iw8C_udEBX-mWxi3DkcBzUR7t4',
    appId: '1:1010428449178:ios:e2517df6a788ffc6242a23',
    messagingSenderId: '1010428449178',
    projectId: 'rumour-90460',
    storageBucket: 'rumour-90460.firebasestorage.app',
    iosBundleId: 'com.example.rumour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCJAbn9iw8C_udEBX-mWxi3DkcBzUR7t4',
    appId: '1:1010428449178:ios:e2517df6a788ffc6242a23',
    messagingSenderId: '1010428449178',
    projectId: 'rumour-90460',
    storageBucket: 'rumour-90460.firebasestorage.app',
    iosBundleId: 'com.example.rumour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUWxRLUj2QIJvmiLGQFbKkqZSOcBccY0',
    appId: '1:1010428449178:web:30a235265875fec1242a23',
    messagingSenderId: '1010428449178',
    projectId: 'rumour-90460',
    authDomain: 'rumour-90460.firebaseapp.com',
    storageBucket: 'rumour-90460.firebasestorage.app',
    measurementId: 'G-VQGVTN56YF',
  );
}
